### ISSUE TITLE
Deprecated methods

### ISSUE THREAD

**Issue by PerSterin** [RubenHarms/ha-harvia-xenio-wifi#2]
Logger: homeassistant.components.number
Source: components/number/__init__.py:223
integration: Number (documentation, issues)
First occurred: 18:06:40 (1 occurrences)
Last logged: 18:06:40

custom_components.harvia_sauna.number::HarviaHumiditySetPoint is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author

**Comment by PerSterin** [comment]
2024-09-21 20:15:11.417 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Harvia Sauna for harvia_sauna
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/harvia_sauna/__init__.py", line 628, in async_setup_entry
await harvia_sauna.async_setup(entry)
File "/config/custom_components/harvia_sauna/__init__.py", line 438, in async_setup
await self.update_devices()
File "/config/custom_components/harvia_sauna/__init__.py", line 492, in update_devices
latestDeviceData = await self.get_latest_device_data(deviceId)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/harvia_sauna/__init__.py", line 458, in get_latest_device_data
deviceData = json.loads(data['data']['getLatestData']['data'])
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by solomal1** [comment]
@RubenHarms Loving the Harvia Sauna Integration!

I noted this error in my Home Assistant Log:

> 2025-11-26 11:30:48.604 WARNING (ImportExecutor_0) [homeassistant.components.number] custom_components.harvia_sauna.number::HarviaHumiditySetPoint is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. **Please report it to the custom integration author**

It doesn't seem to be causing me any issues and I am running Home Assistant 2025.11. 

**Hope you have that on your to-do list.**
